apiVersion: apps/v1
kind: Deployment
metadata:
  name: revalyze-cms
  namespace: revalyze
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revalyze-cms
  template:
    metadata:
      labels:
        app: revalyze-cms
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: cms
          image: nickglas/revalyze-cms:latest
          ports:
            - containerPort: 80
